/**
 * Detects new events by comparing the previous events-index.json with the newly generated one.
 * Outputs new-events.json to the output directory for use by the dispatch step.
 *
 * Usage: npx tsx scripts/detect-new-events.ts
 *
 * Expects:
 *   - previous-events-index.json in the repo root (downloaded from production)
 *   - output/events-index.json (just generated by the build)
 *
 * Outputs:
 *   - output/new-events.json
 */

import * as fs from 'fs'
import * as path from 'path'

interface EventsIndexEntry {
  icsUrl: string
  summary: string
  description?: string
  location?: string
  date: string
  endDate?: string
  url?: string
  lat?: number
  lng?: number
}

export interface NewEventsPayload {
  dispatchId: string
  detectedAt: string
  previousEventCount: number
  currentEventCount: number
  newEvents: EventsIndexEntry[]
}

/**
 * Compute a composite key for an event (matches dedup logic in the Worker and web UI).
 */
export function eventKey(event: EventsIndexEntry): string {
  return `${event.summary}|${event.date}`
}

/**
 * Detect events present in the current index but absent from the previous one.
 */
export function detectNewEvents(
  previousEvents: EventsIndexEntry[],
  currentEvents: EventsIndexEntry[]
): EventsIndexEntry[] {
  const previousKeys = new Set(previousEvents.map(eventKey))
  return currentEvents.filter(event => !previousKeys.has(eventKey(event)))
}

function main() {
  const previousPath = path.resolve('previous-events-index.json')
  const currentPath = path.resolve('output/events-index.json')
  const outputPath = path.resolve('output/new-events.json')

  // Load previous events
  let previousEvents: EventsIndexEntry[] = []
  if (fs.existsSync(previousPath)) {
    try {
      previousEvents = JSON.parse(fs.readFileSync(previousPath, 'utf-8'))
      if (!Array.isArray(previousEvents)) previousEvents = []
    } catch {
      console.warn('Warning: Could not parse previous-events-index.json, treating as empty')
      previousEvents = []
    }
  } else {
    console.warn('Warning: previous-events-index.json not found, treating as empty (all events will be "new")')
  }

  // Load current events
  if (!fs.existsSync(currentPath)) {
    console.error('Error: output/events-index.json not found. Run calendar generation first.')
    process.exit(1)
  }
  let currentEvents: EventsIndexEntry[]
  try {
    currentEvents = JSON.parse(fs.readFileSync(currentPath, 'utf-8'))
    if (!Array.isArray(currentEvents)) {
      console.error('Error: output/events-index.json is not an array')
      process.exit(1)
    }
  } catch (e) {
    console.error('Error: Could not parse output/events-index.json:', e)
    process.exit(1)
  }

  const newEvents = detectNewEvents(previousEvents, currentEvents)

  const dispatchId = process.env.GITHUB_RUN_ID
    ? `run-${process.env.GITHUB_RUN_ID}`
    : `local-${Date.now()}`

  const payload: NewEventsPayload = {
    dispatchId,
    detectedAt: new Date().toISOString(),
    previousEventCount: previousEvents.length,
    currentEventCount: currentEvents.length,
    newEvents,
  }

  fs.writeFileSync(outputPath, JSON.stringify(payload, null, 2))

  // Log summary
  console.log(`Previous events: ${previousEvents.length}`)
  console.log(`Current events: ${currentEvents.length}`)
  console.log(`New events detected: ${newEvents.length}`)

  // Write summary to GitHub Actions
  if (process.env.GITHUB_STEP_SUMMARY) {
    const summary = [
      '## New Event Detection',
      '',
      `| Metric | Count |`,
      `|--------|-------|`,
      `| Previous events | ${previousEvents.length} |`,
      `| Current events | ${currentEvents.length} |`,
      `| **New events** | **${newEvents.length}** |`,
      '',
    ]

    if (newEvents.length > 0 && newEvents.length <= 20) {
      summary.push('### New Events')
      summary.push('')
      for (const event of newEvents) {
        summary.push(`- **${event.summary}** — ${event.date}${event.location ? ` @ ${event.location}` : ''}`)
      }
    } else if (newEvents.length > 20) {
      summary.push(`*${newEvents.length} new events (too many to list individually)*`)
    }

    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summary.join('\n') + '\n')
  }
}

// Only run main when executed directly (not imported for testing)
const isDirectRun = process.argv[1]?.endsWith('detect-new-events.ts') ||
  process.argv[1]?.endsWith('detect-new-events.js')
if (isDirectRun) {
  main()
}
