/**
 * Dispatches new event notifications to the Cloudflare Worker.
 * Called by GitHub Actions after detecting new events.
 *
 * Usage: npx tsx scripts/dispatch-notifications.ts
 *
 * Environment variables:
 *   - WORKER_URL: Base URL of the favorites Worker
 *   - DISPATCH_API_KEY: API key for the dispatch endpoint
 *
 * Expects:
 *   - output/new-events.json (generated by detect-new-events.ts)
 */

import * as fs from 'fs'
import * as path from 'path'

const SANITY_CAP = 500

async function main() {
  const workerUrl = process.env.WORKER_URL
  const apiKey = process.env.DISPATCH_API_KEY

  if (!workerUrl) {
    console.error('Error: WORKER_URL environment variable is required')
    process.exit(1)
  }
  if (!apiKey) {
    console.error('Error: DISPATCH_API_KEY environment variable is required')
    process.exit(1)
  }

  const payloadPath = path.resolve('output/new-events.json')
  if (!fs.existsSync(payloadPath)) {
    console.log('No new-events.json found, skipping dispatch')
    return
  }

  const payload = JSON.parse(fs.readFileSync(payloadPath, 'utf-8'))

  if (!payload.newEvents || payload.newEvents.length === 0) {
    console.log('No new events to dispatch')
    return
  }

  if (payload.newEvents.length > SANITY_CAP) {
    console.warn(`::warning::Too many new events (${payload.newEvents.length}), exceeding sanity cap of ${SANITY_CAP}. Skipping dispatch.`)
    writeSummary(`**Notification dispatch skipped**: ${payload.newEvents.length} new events exceeds sanity cap of ${SANITY_CAP}`)
    return
  }

  console.log(`Dispatching ${payload.newEvents.length} new events (dispatch ID: ${payload.dispatchId})`)

  try {
    const response = await fetch(`${workerUrl}/notifications/dispatch`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Dispatch-API-Key': apiKey,
      },
      body: JSON.stringify(payload),
    })

    const result = await response.json()

    if (!response.ok) {
      console.warn(`::warning::Notification dispatch failed: HTTP ${response.status} — ${JSON.stringify(result)}`)
      writeSummary(`**Notification dispatch failed**: HTTP ${response.status}`)
      return
    }

    console.log(`Dispatch accepted: ${result.batchesEnqueued} batches for ${result.totalUsers} users`)
    writeSummary([
      '## Notification Dispatch',
      '',
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Dispatch ID | \`${result.dispatchId}\` |`,
      `| New events | ${payload.newEvents.length} |`,
      `| Batches enqueued | ${result.batchesEnqueued} |`,
      `| Total subscribers | ${result.totalUsers} |`,
      `| Status | ${result.status} |`,
    ].join('\n'))
  } catch (err) {
    console.warn(`::warning::Notification dispatch error: ${err}`)
    writeSummary(`**Notification dispatch error**: ${err}`)
  }
}

function writeSummary(content: string) {
  if (process.env.GITHUB_STEP_SUMMARY) {
    fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, content + '\n')
  }
}

main()
