AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Authenticated HTTP proxy Lambda with Function URL (SigV4 auth).
  GitHub Actions assumes the output IAM role via OIDC to invoke the proxy,
  which forwards requests from AWS IPs instead of GitHub runner IPs.

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------
Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization or user that owns the repository.

  GitHubRepo:
    Type: String
    Description: GitHub repository name (without the org prefix).

  AllowedTargetDomains:
    Type: CommaDelimitedList
    Description: >
      Comma-separated list of domains the proxy is allowed to fetch
      (e.g. "www.axs.com,graph.amctheatres.com").
      Leave empty to allow all domains (not recommended for production).
    Default: ""

# ---------------------------------------------------------------------------
# Resources
# ---------------------------------------------------------------------------
Resources:

  # -- GitHub OIDC Provider --------------------------------------------------
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        # AWS verifies GitHub's OIDC certs directly; value is required but
        # not used for validation.
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  # -- IAM role that GitHub Actions assumes ----------------------------------
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-github-actions"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubOrg}/${GitHubRepo}:*"
      Policies:
        - PolicyName: InvokeProxyFunctionUrl
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunctionUrl
                Resource: !GetAtt ProxyFunction.Arn

  # -- Lambda execution role -------------------------------------------------
  ProxyFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-lambda-exec"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # -- Lambda function -------------------------------------------------------
  ProxyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-proxy"
      Description: Authenticated HTTP proxy for calendar rippers
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt ProxyFunctionExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ALLOWED_DOMAINS: !Join [",", !Ref AllowedTargetDomains]
      Code:
        # Inline handler – keep in sync with handler.ts (the tested source).
        # Passthrough proxy: ?url=<target>, verb + headers + body forwarded.
        ZipFile: |
          const allowed = (process.env.ALLOWED_DOMAINS || "")
            .split(",").map(d => d.trim()).filter(Boolean);
          const STRIP = new Set(["host","authorization","content-length"]);
          const STRIP_PFX = ["x-amz-","x-forwarded-"];
          const STRIP_RES = new Set(["transfer-encoding","connection","content-encoding","content-length"]);

          exports.handler = async (event) => {
            const target = event.queryStringParameters?.url;
            if (!target) return {statusCode:400, headers:{}, body:"Missing required query parameter: url"};
            let hostname;
            try { hostname = new URL(target).hostname; }
            catch { return {statusCode:400, headers:{}, body:"Invalid URL"}; }
            if (allowed.length > 0 &&
                !allowed.some(d => hostname === d || hostname.endsWith("."+d)))
              return {statusCode:403, headers:{}, body:"Domain not allowed: "+hostname};
            const method = event.requestContext.http.method;
            const hdrs = {};
            for (const [k,v] of Object.entries(event.headers||{})) {
              const l = k.toLowerCase();
              if (STRIP.has(l) || STRIP_PFX.some(p => l.startsWith(p))) continue;
              hdrs[k] = v;
            }
            const opts = {method, headers: hdrs};
            if (event.body && method !== "GET" && method !== "HEAD")
              opts.body = event.isBase64Encoded
                ? Buffer.from(event.body,"base64").toString() : event.body;
            try {
              const res = await fetch(target, opts);
              const body = await res.text();
              const rh = {};
              res.headers.forEach((v,k) => { if (!STRIP_RES.has(k)) rh[k]=v; });
              return {statusCode: res.status, headers: rh, body};
            } catch(e) {
              return {statusCode:502, headers:{}, body:"Proxy request failed: "+e.message};
            }
          };

  # -- Function URL with IAM auth -------------------------------------------
  ProxyFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: AWS_IAM
      TargetFunctionArn: !GetAtt ProxyFunction.Arn

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
Outputs:
  ProxyFunctionUrl:
    Description: >
      Lambda Function URL. Store as a GitHub Actions secret
      (e.g. PROXY_FUNCTION_URL) and use it in your rippers.
    Value: !GetAtt ProxyFunctionUrl.FunctionUrl

  GitHubActionsRoleArn:
    Description: >
      IAM role ARN for GitHub Actions to assume via OIDC. Add this as a
      GitHub Actions secret (e.g. AWS_ROLE_ARN) and configure the
      aws-actions/configure-aws-credentials action with it.
    Value: !GetAtt GitHubActionsRole.Arn

  ProxyFunctionArn:
    Description: Lambda function ARN (for reference / debugging).
    Value: !GetAtt ProxyFunction.Arn
